apiVersion: v1
kind: Pod
metadata:
  name: podtest1
  labels:
    name: nginx
    app: test
    env: dev
spec:
  containers:
  - name: test1
    image: nginx
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    # ports:
    #   - containerPort: <Port>
