# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    stdin_open: true
    tty: true
    container_name: jenkins-lts
    volumes:
      - /Allinone/docker_volumes_central/jenkins-lts-vol/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock