AWSTemplateFormatVersion: "2010-09-09"
Description: EKS ARGOCD VPC Stack

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref My-ARGOCD-VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-south-1a

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref My-ARGOCD-VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-south-1b
