AWSTemplateFormatVersion: "2010-09-09"
Description: EKS IAM Roles Stack

Resources:
  EKSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eks-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole

  EKSNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eks-node-group-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
